# Generated by Django 4.1.7 on 2023-07-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.TextField(default='', max_length=50),
        ),
    ]
