# Generated by Django 4.2.4 on 2023-08-03 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_book', '0003_post_alter_profile_firstname_alter_profile_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 20, 55, 6, 791239)),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=' ', upload_to='post_images'),
        ),
    ]
